# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'')),
            ],
            options={
                'verbose_name': '\u0424\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u044f',
                'verbose_name_plural': '\u0424\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u0438',
            },
        ),
        migrations.CreateModel(
            name='Photo_album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='\u0418\u043c\u044f \u0430\u043b\u044c\u0431\u043e\u043c\u0430')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430')),
            ],
            options={
                'verbose_name': '\u0424\u043e\u0442\u043e\u0430\u043b\u044c\u0431\u043e\u043c',
                'verbose_name_plural': '\u0424\u043e\u0442\u043e\u0430\u043b\u044c\u0431\u043e\u043c\u044b',
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='photo_album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='photo_albums.Photo_album'),
        ),
    ]
