# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_albums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='name',
            field=models.CharField(default='Name', max_length=75),
            preserve_default=False,
        ),
    ]
