# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_albums', '0002_photo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='photo_albums/photos'),
        ),
    ]
