# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_albums', '0003_auto_20170206_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_cover',
            field=models.BooleanField(default=False),
        ),
    ]
