# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-03 07:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_videos_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videos',
            options={'verbose_name': 'Video'},
        ),
    ]
