# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20170203_0704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videos',
            options={'verbose_name': '\u0412\u0438\u0434\u0435\u043e', 'verbose_name_plural': '\u0412\u0438\u0434\u0435\u043e'},
        ),
    ]
