# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20170206_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, upload_to='albums/static'),
        ),
    ]
