# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20170206_0925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_date'], 'verbose_name': '\u041d\u043e\u0432\u043e\u0441\u0442\u0438', 'verbose_name_plural': '\u041d\u043e\u0432\u043e\u0441\u0442\u0438'},
        ),
    ]
