branch-defaults:
  master:
    environment: mysite-test
global:
  application_name: mysite
  branch: null
  default_ec2_keyname: keypair
  default_platform: Python 3.4
  default_region: eu-west-2
  profile: eb-cli
  repository: null
  sc: git
