# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_auto_20170203_0717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': '\u0410\u043b\u044c\u0431\u043e\u043c', 'verbose_name_plural': '\u0410\u043b\u044c\u0431\u043e\u043c\u044b'},
        ),
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(upload_to='albums/static', verbose_name='\u041e\u0431\u043b\u043e\u0436\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='album',
            name='link',
            field=models.URLField(max_length=100, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 \u0430\u043b\u044c\u0431\u043e\u043c'),
        ),
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=75, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0430\u043b\u044c\u0431\u043e\u043c\u0430'),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_year',
            field=models.CharField(max_length=4, verbose_name='\u0413\u043e\u0434 \u0432\u044b\u043f\u0443\u0441\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='album',
            name='songs_list',
            field=tinymce.models.HTMLField(blank=True, verbose_name='\u0421\u043f\u0438\u0441\u043e\u043a \u043f\u0435\u0441\u0435\u043d'),
        ),
    ]
